/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.IntegrationTestResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import javax.validation.Valid;
import javax.validation.constraints.*;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-01-11T03:29:22.478Z")

@Api(value = "integrationTest", description = "the integrationTest API")
public interface IntegrationTestApi {

    @ApiOperation(value = "Run integration tests against remote API", nickname = "integrationTestGet", notes = "", response = IntegrationTestResult.class, tags={ "test", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = IntegrationTestResult.class) })
    @RequestMapping(value = "/integrationTest",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<IntegrationTestResult> integrationTestGet(@NotNull @ApiParam(value = "base url of remote API to test", required = true) @Valid @RequestParam(value = "url", required = true) String url);

}
